apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: debug-user-rolebinding
  namespace: default # Should be namespace you are granting access to
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: debug-user-role # Should match name of Role
subjects:
- namespace: default
  kind: ServiceAccount
  name: debug-user # Should match service account name, above